### ISSUE TITLE
Wrong URL for subscriber

### ISSUE THREAD

**Issue by Marcel40625** [Axiacore/cachet-uptime-robot#38]
after i changing the config for using 

> CachetUrl = http://127.0.0.1

it can finally connect but now when a status is changing the subscribers are getting a mail with URL "http://127.0.0.1"

http://img.fly-host.eu/images/png/p4cFF.png

How to get rid of this?

**Comment by MarcHagen** [comment]
Hi there,
That's not specific to this package, you should config that in CachetHQ itself.
Go to you're `CachetHQ dashboard > Settings > APPLICATION SETUP > Site URL & Site Name`

This means #37 is fixed?

**Comment by Marcel40625** [comment]
> Go to you're CachetHQ dashboard > Settings > APPLICATION SETUP > Site URL & Site Name

there is the correct URL setup ... it seems that the mail system pulls the ip from where the api was reached at

when i update manually via the dashboard it sends the email with the correct domain, when i let the script update its localhost

> This means #37 is fixed?

Not realy still cant connect via the public domain ... only through localhost
